/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PastRouteImport } from './routes/past'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminScannerRouteImport } from './routes/admin.scanner'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminEventIdEditRouteImport } from './routes/admin.$eventId.edit'

const PastRoute = PastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventIdEditRoute = AdminEventIdEditRouteImport.update({
  id: '/$eventId/edit',
  path: '/$eventId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/past': typeof PastRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/$eventId/edit': typeof AdminEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/past': typeof PastRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin/$eventId/edit': typeof AdminEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/past': typeof PastRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/$eventId/edit': typeof AdminEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/past'
    | '/admin/new'
    | '/admin/scanner'
    | '/admin/tickets'
    | '/events/$eventId'
    | '/ticket/$ticketId'
    | '/admin/'
    | '/events/'
    | '/admin/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/past'
    | '/admin/new'
    | '/admin/scanner'
    | '/admin/tickets'
    | '/events/$eventId'
    | '/ticket/$ticketId'
    | '/admin'
    | '/events'
    | '/admin/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/past'
    | '/admin/new'
    | '/admin/scanner'
    | '/admin/tickets'
    | '/events/$eventId'
    | '/ticket/$ticketId'
    | '/admin/'
    | '/events/'
    | '/admin/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PastRoute: typeof PastRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$eventId/edit': {
      id: '/admin/$eventId/edit'
      path: '/$eventId/edit'
      fullPath: '/admin/$eventId/edit'
      preLoaderRoute: typeof AdminEventIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNewRoute: typeof AdminNewRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventIdEditRoute: typeof AdminEventIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewRoute: AdminNewRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventIdEditRoute: AdminEventIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PastRoute: PastRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
